# Generated by Django 4.2.13 on 2026-06-02 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.FloatField(default=5.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sectors',
                'indexes': [models.Index(fields=['code'], name='sectors_code_9c3b36_idx'), models.Index(fields=['is_active'], name='sectors_is_acti_1f0448_idx')],
            },
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], default='motorcycle', max_length=50)),
                ('vehicle_plate', models.CharField(blank=True, max_length=50)),
                ('max_packages_per_day', models.IntegerField(default=50)),
                ('current_packages_count', models.IntegerField(default=0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livreurs', to='deliveries.sector')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'livreurs',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verification_tokens',
            },
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('delivery_address', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('contents', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('express', 'Express'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned to Livreur'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='deliveries.livreur')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_list', to='deliveries.sector')),
            ],
            options={
                'db_table': 'colis',
            },
        ),
        migrations.AddIndex(
            model_name='livreur',
            index=models.Index(fields=['sector', 'status'], name='livreurs_sector__3088e1_idx'),
        ),
        migrations.AddIndex(
            model_name='livreur',
            index=models.Index(fields=['user'], name='livreurs_user_id_0590a5_idx'),
        ),
        migrations.AddIndex(
            model_name='colis',
            index=models.Index(fields=['tracking_number'], name='colis_trackin_740b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='colis',
            index=models.Index(fields=['status', 'sector'], name='colis_status_fa9d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='colis',
            index=models.Index(fields=['livreur', 'status'], name='colis_livreur_664b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='colis',
            index=models.Index(fields=['created_at'], name='colis_created_ecd996_idx'),
        ),
    ]
