# Generated by Django 4.2.13 on 2026-04-18 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='reservations.reservation'),
        ),
        migrations.AddIndex(
            model_name='flightcache',
            index=models.Index(fields=['origin', 'destination', 'departure_date'], name='flight_cach_origin_66caa9_idx'),
        ),
        migrations.AddIndex(
            model_name='flightcache',
            index=models.Index(fields=['expires_at'], name='flight_cach_expires_faac6a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'status'], name='reservation_user_id_d4fda7_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['external_order_id'], name='reservation_externa_1c0386_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['created_at'], name='reservation_created_0fc9f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('user', 'offer_id'), name='unique_active_user_offer'),
        ),
        migrations.AddIndex(
            model_name='passenger',
            index=models.Index(fields=['reservation'], name='passengers_reserva_5e5fa5_idx'),
        ),
    ]
