# Generated by Django 4.2.13 on 2026-04-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pending_booking_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
