# Generated by Django 4.2.13 on 2026-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_add_promo_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('emis', 'Émis'), ('cancelled', 'Annulée'), ('failed', 'Échouée')], db_index=True, default='pending', max_length=20),
        ),
    ]
