# Generated by Django 4.2.13 on 2026-06-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('reservations', '0005_add_emis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billets', to='deliveries.livreur'),
        ),
    ]
